version: '3.7'
services:
  db:
    image: postgres:15
    container_name: pc_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7
    container_name: pc_redis

  pc:
    image: pc_image
    build:
      context: .
    env_file:
      - .env-non-dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: bash -c "alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 1234:8000
